sudo: required
addons:
  apt:
    packages:
    - git
    - make
    - curl
env:
- DOCKER_IMAGE_NAME=cloudposse/openvpn
services:
- docker
install:
- make init
- make docker:login

script:
- make ARGS="GITHUB_TOKEN=$(echo $GITHUB_TOKEN)" docker:build-with-args

after_success:
- make travis:docker-tag-and-push
