#!/bin/bash

NAMESPACE=${NAMESPACE:-default}
TYPE=${TYPE:-Opaque}

if [ -z "$SECRET_NAME" ]; then
    echo "ERROR: Secret name is empty or unset"
    exit 1
fi

PKI_DIR=/etc/openvpn/pki

KEY=$(cat $PKI_DIR/private/${EASYRSA_REQ_CN}.key | base64 )
CA=$(cat $PKI_DIR/ca.crt | base64 )
CERT=$(cat $PKI_DIR/issued/${EASYRSA_REQ_CN}.crt | base64 )
DH=$(cat $PKI_DIR/dh.pem | base64 )
TLS_AUTH=$(cat $PKI_DIR/ta.key | base64 )
CONFIG=$(cat /etc/openvpn/openvpn.conf | base64 )
ENV_VARS=$(cat /etc/openvpn/ovpn_env.sh | base64 )


kubectl get secrets --namespace $NAMESPACE $SECRET_NAME && ACTION=replace || ACTION=create;

cat << EOF | kubectl $ACTION -f -
{
 "apiVersion": "v1",
 "kind": "Secret",
 "metadata": {
   "name": "$SECRET_NAME",
   "namespace": "$NAMESPACE"
 },
 "data": {
   "key": "$KEY",
   "ca": "$CA",
   "cert": "$CERT",
   "dh": "$DH",
   "tls_auth": "$TLS_AUTH",
   "config": "$CONFIG",
   "vars": "$ENV_VARS"
 },
 "type": "$TYPE"
}
EOF