#!/usr/bin/with-contenv bash

if [ "${MFA_PROVIDER}" == "google-authenticator" ]; then
  echo "- Enabling Google Authenticator"

  cp /cloudposse/templates/pam/google-authenticator > /etc/pam.d/openvpn
fi
